version: '3.9'

services:
  webapp:
    command: > 
      sh -c "gunicorn conf.wsgi:application --bind 0.0.0.0:8000"
    container_name: django_web
    build: 
      context: .
    expose:
      - 8000
    env_file:
      - .env
    volumes:
      - static_files:/app/static
      - ./:/app

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - 80:80
    depends_on:
      - webapp
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - static_files:/home/app/static

volumes:
  static_files: